version: '3.8'
services:
  app:
    build:
      context: .
      network: host
    command: dev
    volumes:
      - .:/home/bun/app
    networks:
      - docker_default
      - default
    labels:
      - "traefik.http.routers.twit.rule=Host(`twit.localhost`)"
      - "traefik.http.routers.twit.tls=true"

networks:
  docker_default:
    external: true
    name: docker_default
